Revert "Libcamera: try an other one"
This reverts commit 501ee69efa77649c4ec3ac68378a1faa4f7ebed4.
Build error:

In file included from device/htc/buzz/libcamera/cameraHal.cpp:35:
hardware/qcom/display/libgralloc/gralloc_priv.h:101: error: conflicting declaration 'GRALLOC_MODULE_PERFORM_CREATE_HANDLE_FROM_BUFFER'
device/htc/buzz/include/hardware/gralloc.h:108: error: 'GRALLOC_MODULE_PERFORM_CREATE_HANDLE_FROM_BUFFER' has a previous declaration as '<anonymous enum> GRALLOC_MODULE_PERFORM_CREATE_HANDLE_FROM_BUFFER'
device/htc/buzz/libcamera/cameraHal.cpp: In function 'bool CameraHAL_CopyBuffers_Hw(int, int, size_t, size_t, int, int, int, int, int, int)':
device/htc/buzz/libcamera/cameraHal.cpp:128: error: 'struct mdp_blit_req' has no member named 'sharpening_strength'