Gralloc: fix build
Got this error:

    hardware/qcom/display/libgralloc/gralloc_priv.h:98:56: error: conflicting declaration 'GRALLOC_MODULE_PERFORM_CREATE_HANDLE_FR
    device/htc/buzz/include/hardware/gralloc.h:108:5: error: 'GRALLOC_MODULE_PERFORM_CREATE_HANDLE_FROM_BUFFER' has a previous dec

So I removed the declaration of GRALLOC_MODULE_PERFORM_CREATE_HANDLE_FROM_BUFFER as the declaration was identical.
Removal of the declaration in the device repo results in build errors.

Change-Id: If9297b402a1c9a6706007c2eccc2ba662b2e327a